#!/usr/bin/env bash
# Fake claude binary for forza integration tests.
#
# Controlled by environment variables:
#   FAKE_CLAUDE_OUTPUT      - text to return (default: "fake response")
#   FAKE_CLAUDE_EXIT_CODE   - exit code to return (default: 0)
#   FAKE_CLAUDE_COST_USD    - cost in JSON output (default: 0.01)
#   FAKE_CLAUDE_DELAY       - seconds to sleep before output (default: 0)
#   FAKE_CLAUDE_TOUCH_FILE  - if set, creates this file in the working dir
#                             (simulates agent making changes)
#
# Outputs NDJSON matching claude's stream-json format.

OUTPUT="${FAKE_CLAUDE_OUTPUT:-fake response}"
EXIT_CODE="${FAKE_CLAUDE_EXIT_CODE:-0}"
COST_USD="${FAKE_CLAUDE_COST_USD:-0.01}"
DELAY="${FAKE_CLAUDE_DELAY:-0}"

if [[ "$DELAY" -gt 0 ]]; then
    sleep "$DELAY"
fi

if [[ "$EXIT_CODE" -ne 0 ]]; then
    echo "stage failed" >&2
    exit "$EXIT_CODE"
fi

# Simulate agent making changes if requested.
if [[ -n "$FAKE_CLAUDE_TOUCH_FILE" ]]; then
    echo "// generated by fake-claude" > "$FAKE_CLAUDE_TOUCH_FILE"
    # Stage and commit in the working dir.
    git -C "$(dirname "$FAKE_CLAUDE_TOUCH_FILE")" add -A 2>/dev/null
    git -C "$(dirname "$FAKE_CLAUDE_TOUCH_FILE")" commit -m "automation: fake changes" --allow-empty 2>/dev/null
fi

# Parse --output-format from args.
OUTPUT_FORMAT=""
for arg in "$@"; do
    if [[ "$prev" == "--output-format" ]]; then
        OUTPUT_FORMAT="$arg"
    fi
    prev="$arg"
done

ESCAPED_OUTPUT=$(printf '%s' "$OUTPUT" | sed 's/\\/\\\\/g; s/"/\\"/g; s/	/\\t/g')

if [[ "$OUTPUT_FORMAT" == "stream-json" ]]; then
    printf '{"type":"system","subtype":"init","session_id":"fake-session","tools":[],"mcp_servers":[]}\n'
    printf '{"type":"assistant","message":{"id":"msg_fake","type":"message","role":"assistant","content":[{"type":"text","text":"%s"}],"model":"claude-fake","stop_reason":"end_turn","stop_sequence":null,"usage":{"input_tokens":5,"output_tokens":3}},"session_id":"fake-session"}\n' "$ESCAPED_OUTPUT"
    printf '{"type":"result","subtype":"success","result":"%s","session_id":"fake-session","cost_usd":%s,"total_cost_usd":%s,"num_turns":1,"is_error":false}\n' "$ESCAPED_OUTPUT" "$COST_USD" "$COST_USD"
elif [[ "$OUTPUT_FORMAT" == "json" ]]; then
    printf '{"result":"%s","session_id":"fake-session","total_cost_usd":%s,"num_turns":1,"is_error":false}\n' "$ESCAPED_OUTPUT" "$COST_USD"
else
    printf '%s\n' "$OUTPUT"
fi

exit 0
